### ISSUE TITLE
pip Support

### ISSUE THREAD

**Issue by frankV** [dbtsai/python-pushwoosh#2]
Would really appreciate being able to install this from pip. I think a resource like this should be available on pypi anyway.

For developers finding this a problem, you can install from the repository:
```pip install git+git://github.com/Pushwoosh/pushwoosh-python-lib.git```

**Comment by dbtsai** [comment]
I am no longer maintaining this package anymore. Thanks.

**Comment by frankV** [comment]
My apologies, I made this on the wrong library!
